CREATE TABLE `user` (
`id` INT(11) unsigned NOT NULL AUTO_INCREMENT,
`user_name` VARCHAR(32) DEFAULT NULL,
`password` VARCHAR(32) DEFAULT NULL,
`name` VARCHAR(32) DEFAULT NULL,
`email` VARCHAR(32) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;